language: node_js
node_js:
  - "8"
install: npm install
jobs:
  include:
    - stage: lint
      script: npm run test:lint
    - stage: coverage
      script: bash ./scripts/.travis-coverage.sh
    - stage: deploy
      script: bash ./scripts/.travis-deploy.sh
cache:
  directories:
    - node_modules
notifications:
  email: false
